CREATE TABLE IF NOT EXISTS analysis_index (key TEXT PRIMARY KEY, response TEXT NOT NULL, updated_at TEXT NOT NULL, checked_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS research_jobs (key TEXT PRIMARY KEY, next_at INTEGER NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS research_budget (day TEXT PRIMARY KEY, used INTEGER NOT NULL);
