"""Reported numeric facts come from SEC XBRL, never generated by the model."""
import json
import math
import logging
import httpx
from app.sec import _get
from app.collection import now, age
from app.database import SessionLocal
from app.models import ReportedFacts
from sqlalchemy.exc import IntegrityError

TAGS = {
    "Revenue": ["RevenueFromContractWithCustomerExcludingAssessedTax", "Revenues", "SalesRevenueNet"],
    "Net income (loss)": ["NetIncomeLoss", "ProfitLoss"],
    "Operating cash flow": ["NetCashProvidedByUsedInOperatingActivities"],
    "Cash and equivalents": ["CashAndCashEquivalentsAtCarryingValue"],
    "Long-term debt (noncurrent)": ["LongTermDebtNoncurrent"],
    "Long-term debt (current portion)": ["LongTermDebtCurrent"],
}


def extract(data, filing):
    if int(data.get("cik", -1)) != int(filing["cik"]):
        raise ValueError("XBRL issuer mismatch")
    facts = []
    taxonomy = data.get("facts", {}).get("us-gaap", {})
    for label, tags in TAGS.items():
        found = []
        for tag in tags:
            for unit, rows in taxonomy.get(tag, {}).get("units", {}).items():
                for row in rows:
                    value = row.get("val")
                    if (row.get("accn") != filing["accession"] or not row.get("end")
                            or not isinstance(value, (int, float)) or isinstance(value, bool)
                            or not math.isfinite(value)):
                        continue
                    found.append({"label": label, "value": value, "unit": unit,
                                  "period_start": row.get("start"), "period_end": row["end"],
                                  "filed": row.get("filed"), "form": row.get("form"),
                                  "tag": f"us-gaap:{tag}", "accession": row["accn"],
                                  "source_url": filing["url"]})
            if found:
                break  # Prefer one revenue concept; never sum overlapping tags.
        seen = set()
        for fact in found:
            identity = (fact["unit"], fact["period_start"], fact["period_end"], fact["value"])
            if identity not in seen:
                facts.append(fact)
                seen.add(identity)
    return facts


def get_reported_facts(filing):
    missing = {"items": [], "status": "unavailable", "note": "Structured financial facts are unavailable for this filing. Missing values are not zero."}
    if not filing.get("cik") or not filing.get("accession"):
        return missing
    with SessionLocal() as db:
        cached = db.get(ReportedFacts, filing["accession"])
        if cached and age(cached.updated_at) < 86400:
            return json.loads(cached.response)
    try:
        data = json.loads(_get(f'https://data.sec.gov/api/xbrl/companyfacts/CIK{int(filing["cik"]):010d}.json'))
        items = extract(data, filing)
        result = {"items": items, "status": "available" if items else "not_reported",
                  "note": "SEC XBRL values from this exact filing; periods and units may differ. Coverage is limited to standard US-GAAP tags. Missing values are not zero."}
    except (httpx.HTTPError, ValueError, KeyError, TypeError, AttributeError) as exc:
        # Fail independently: a missing XBRL file must not disable excerpt analysis.
        logging.getLogger(__name__).warning("Structured facts unavailable: %s", type(exc).__name__)
        return missing
    with SessionLocal() as db:
        row = db.get(ReportedFacts, filing["accession"])
        if row is None:
            row = ReportedFacts(accession=filing["accession"], cik=filing["cik"])
            db.add(row)
        row.response, row.updated_at = json.dumps(result), now()
        try:
            db.commit()
        except IntegrityError:
            db.rollback()
    return result
